# Generated by Django 5.2.8 on 2026-01-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_seoulrestaurantlicense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoulrestaurantlicense',
            options={'verbose_name': '영등포구 편의점 인허가', 'verbose_name_plural': '영등포구 편의점 인허가 목록'},
        ),
        migrations.AddField(
            model_name='seoulrestaurantlicense',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='seoulrestaurantlicense',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='seoulrestaurantlicense',
            name='x',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='좌표X (TM)'),
        ),
        migrations.AlterField(
            model_name='seoulrestaurantlicense',
            name='y',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='좌표Y (TM)'),
        ),
        migrations.AlterModelTable(
            name='seoulrestaurantlicense',
            table='yeongdeungpo_convenience_license',
        ),
    ]
