# Generated by Django 5.2.8 on 2026-01-16 05:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_convert_coordinates_to_latlon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TobaccoRetailLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgtno', models.CharField(max_length=100, unique=True, verbose_name='관리번호')),
                ('opnsfteamcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='개방자치단체코드')),
                ('bplcnm', models.CharField(max_length=200, verbose_name='사업장명')),
                ('uptaenm', models.CharField(blank=True, max_length=100, null=True, verbose_name='업태구분명')),
                ('trdstategbn', models.CharField(blank=True, max_length=10, null=True, verbose_name='영업상태코드')),
                ('trdstatenm', models.CharField(blank=True, max_length=50, null=True, verbose_name='영업상태명')),
                ('dtlstategbn', models.CharField(blank=True, max_length=10, null=True, verbose_name='상세영업상태코드')),
                ('dtlstatenm', models.CharField(blank=True, max_length=50, null=True, verbose_name='상세영업상태명')),
                ('apvpermymd', models.CharField(blank=True, max_length=20, null=True, verbose_name='인허가일자')),
                ('apvcancelymd', models.CharField(blank=True, max_length=20, null=True, verbose_name='인허가취소일자')),
                ('dcbymd', models.CharField(blank=True, max_length=20, null=True, verbose_name='폐업일자')),
                ('clgstdt', models.CharField(blank=True, max_length=20, null=True, verbose_name='휴업시작일자')),
                ('clgenddt', models.CharField(blank=True, max_length=20, null=True, verbose_name='휴업종료일자')),
                ('ropnymd', models.CharField(blank=True, max_length=20, null=True, verbose_name='재개업일자')),
                ('sitewhladdr', models.CharField(blank=True, max_length=300, null=True, verbose_name='지번주소')),
                ('rdnwhladdr', models.CharField(blank=True, max_length=300, null=True, verbose_name='도로명주소')),
                ('sitepostno', models.CharField(blank=True, max_length=10, null=True, verbose_name='소재지우편번호')),
                ('rdnpostno', models.CharField(blank=True, max_length=10, null=True, verbose_name='도로명우편번호')),
                ('sitetel', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
                ('sitearea', models.CharField(blank=True, max_length=50, null=True, verbose_name='소재지면적')),
                ('x', models.CharField(blank=True, max_length=50, null=True, verbose_name='좌표X (TM)')),
                ('y', models.CharField(blank=True, max_length=50, null=True, verbose_name='좌표Y (TM)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='위치')),
                ('lastmodts', models.CharField(blank=True, max_length=30, null=True, verbose_name='최종수정일자')),
                ('updategbn', models.CharField(blank=True, max_length=10, null=True, verbose_name='데이터갱신구분')),
                ('updatedt', models.CharField(blank=True, max_length=30, null=True, verbose_name='데이터갱신일자')),
                ('asgnymd', models.CharField(blank=True, max_length=20, null=True, verbose_name='지정일자')),
                ('mwsrnm', models.CharField(blank=True, max_length=100, null=True, verbose_name='민원종류명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '영등포구 담배소매업 인허가',
                'verbose_name_plural': '영등포구 담배소매업 인허가 목록',
                'db_table': 'yeongdeungpo_tobacco_retail_license',
            },
        ),
    ]
