# Generated by Django 5.2.8 on 2026-01-16 06:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_tobaccoretaillicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClosureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=50, unique=True, verbose_name='카카오 Place ID')),
                ('name', models.CharField(max_length=200, verbose_name='매장명')),
                ('address', models.CharField(max_length=300, verbose_name='주소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='위치')),
                ('status', models.CharField(choices=[('정상', '정상 영업'), ('폐업', '폐업 추정')], max_length=10, verbose_name='상태')),
                ('match_reason', models.CharField(max_length=100, verbose_name='매칭 이유')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='체크 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 생성일')),
            ],
            options={
                'verbose_name': '폐업 매장 체크 결과',
                'verbose_name_plural': '폐업 매장 체크 결과 목록',
                'db_table': 'store_closure_result',
                'ordering': ['-checked_at'],
            },
        ),
    ]
